name: dart_chromecast
version: 0.3.3
description: Pure dart package to cast videos to your ChromeCast device and control their playback
homepage: https://github.com/terrabythia/dart_chromecast

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  universal_io: ^2.0.4
  protobuf: ^2.1.0
  http: ^0.13.5
  cli_util: ^0.3.5
  args: ^2.3.1
  xml: ">=5.3.1 <7.0.0"
  logging: ^1.1.0
  multicast_dns: ^0.3.2+2
