name: dart_chromecast
version: 0.2.4
description: Cast videos to your ChromeCast device using Dart
homepage: https://github.com/terrabythia/dart_chromecast

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  protobuf: ^2.0.0
  protoc_plugin: ^20.0.0
  http: ^0.13.1
  cli_util: ^0.3.0
  args: ^2.0.0
  xml: ^5.1.0
  logging: ^1.0.1
  multicast_dns: ^0.3.0
